#!/bin/bash
# 0-world_wide_web: Display DNS record info about subdomains

domain=$1
subdomain=$2

get_subdomain_info() {
    local d=$1
    local s=$2

    dig "$s.$d" +noall +answer | awk -v subd="$s" '
    {
        if ($1 ~ subd"\\.") {
            print "The subdomain " subd " is a " $4 " record and points to " $5
        }
    }'
}

if [ -z "$subdomain" ]; then
    for sub in www lb-01 web-01 web-02; do
        get_subdomain_info "$domain" "$sub"
    done
else
    get_subdomain_info "$domain" "$subdomain"
fi

